apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends-service
  template:
    metadata:
      labels:
        app: friends-service
    spec:
      containers:
      - name: friends-deployment
        image: panagiotisptr/friends-amd64
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: REDIS_ADDRESS
            value: "redis-service:6379"
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"
          - name: USER_SERVICE_ADDR
            value: "user-service:80"

---
apiVersion: v1
kind: Service
metadata:
  name: friends-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: friends-service
