apiVersion: apps/v1
kind: Deployment
metadata:
  name: friends-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: friends-service
  template:
    metadata:
      labels:
        app: friends-service
    spec:
      containers:
      - name: friends-deployment
        image: panagiotisptr/friends
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: REDIS_ADDRESS
            value: "friends-redis-master:6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: friends-redis
                key: redis-password
                optional: false
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: friends-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: friends-service
