apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-deployment
        image: panagiotisptr/authentication
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: REDIS_ADDRESS
            value: "authentication-redis-master:6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentication-redis
                key: redis-password
                optional: false
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: authentication-service
