apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: user-kibana
spec:
  version: 8.4.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: user-elasticsearch
