apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
      - name: user-deployment
        image: panagiotisptr/user
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:                     # Environment variables passed to the container
          - name: LISTEN_PORT
            value: "8080"
          - name: REDIS_ADDRESS
            value: "redis-user"    
          - name: REDIS_PASSWORD
            value: ""
          - name: REDIS_DB
            value: 0
          - name: GRPC_REFLECTION
            value: "true"
          - name: ES_ADDRESSES
            value: "es-user-es-http"
          - name: ES_USERNAME
            value: "elastic"
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: es-user-es-elastic-user
                key: elastic
                optional: false
          - name: ES_CERT_PATH

type: post
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-redis-app-service     # Unique name of the resource
spec:
  type: NodePort                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-redis-app            # Map any pod with label `app=go-redis-app` to this service
