# Elasticsearch Deployment - one node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-service
  template:
    metadata:
      labels:
        app: elasticsearch-service
    spec:
      containers:
      - name: elasticsearch-deployment
        image: elasticsearch:8.4.2
        ports:
          - containerPort: 9200
            protocol: TCP
        env:
          - name: "xpack.security.enabled"
            value: "false"
          - name: "discovery.type"
            value: "single-node"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch-service
---
# Kibana Deployment - also one node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-service
  template:
    metadata:
      labels:
        app: kibana-service
    spec:
      containers:
      - name: kibana-deployment
        image: docker.elastic.co/kibana/kibana:8.4.2
        ports:
          - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  ports:
  - name: http
    port: 5601
    targetPort: 5601
  selector:
    app: kibana-service
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron3
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
# Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
      - name: mongo-deployment
        image: mongo:5
        ports:
          - containerPort: 27017
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=mongo-rs --bind_ip_all"]
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - name: http
    port: 27017
    targetPort: 27017
  selector:
    app: mongo-service
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-deployment
        image: redis
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - name: http
    port: 6379
    targetPort: 6379
  selector:
    app: redis-service
---
# Monstache Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-service
  template:
    metadata:
      labels:
        app: monstache-service
    spec:
      containers:
      - name: monstache-deployment
        image: rwynn/monstache:rel6
        command: ["monstache"]
        args: ["-mongo-url=mongodb://mongo-service:27017", "-elasticsearch-url=http://elasticsearch-service:9200"]
