apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-deployment
        image: panagiotisptr/user-amd64
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: REDIS_ADDRESS
            value: "redis-service:6379"
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"
          - name: ES_ADDRESSES
            value: "http://elasticsearch-service:9200"
          - name: ES_USERNAME
            value: "elastic"
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: user-server
