apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-deployment
        image: panagiotisptr/user
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: REDIS_ADDRESS
            value: "user-redis-master:6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-redis
                key: redis-password
                optional: false
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"
          - name: ES_ADDRESSES
            value: "http://user-elasticsearch-es-http:9200"
          - name: ES_USERNAME
            value: "elastic"
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-elasticsearch-es-elastic-user
                key: elastic
                optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: user-service
