apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
      - name: messaging-deployment
        image: panagiotisptr/messaging-amd64
        ports:
          - containerPort: 80
        env:
          - name: LISTEN_PORT
            value: "80"
          - name: FRIENDS_SERVICE_ADDR
            value: "friends-service"
          - name: REDIS_ADDRESS
            value: "messaging-redis-master:6379"
          - name: REDIS_DB
            value: "0"
          - name: GRPC_REFLECTION
            value: "true"
          - name: ES_ADDRESSES
            value: "http://messaging-elasticsearch-es-http:9200"
          - name: ES_USERNAME
            value: "elastic"
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: messaging-service
