name: User Service PR Workflow

on:
  pull_request:
    paths:
      - 'services/user/**'

jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          locale: "UK"

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install git
        run: sudo apt-get install git

      - name: Install make
        run: sudo apt-get install make

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Make protos
        run: make protos-go

      - name: Mod tidy
        working-directory: ./services/user
        run: go mod tidy

      - uses: gwatts/go-coverage-action@v1
        id: coverage
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: user-test
        with:
          working-directory: ./services/user
          coverage-threshold: 0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install git
        run: sudo apt-get install git

      - name: Install make
        run: sudo apt-get install make

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Make protos
        run: make protos-go

      - name: Mod tidy
        working-directory: ./services/user
        run: go mod tidy

      - name: Test
        working-directory: ./services/user
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: user-test
        run: go test -count=1 ./...
